# Generated by Django 5.0 on 2024-02-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_pack_food_number_people'),
        ('restaurant', '0006_admin_restaurantowner_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='foodigredient',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodigredient',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='menu',
            name='foods',
            field=models.ManyToManyField(related_name='menus', to='food.food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(related_name='orders', to='food.food'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='FoodIgredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
